xinput --set-prop "Kingston HyperX Pulsefire Surge" "libinput Accel Profile Enabled" 0, 1 & # Disable mouse acceleration
xinput --set-prop "Kingston HyperX Pulsefire Surge" "libinput Accel Speed" 0 & # Disable mouse acceleration
xinput --set-prop "ETPS/2 Elantech Touchpad" "libinput Natural Scrolling Enabled" 1 # Enable trackpad natural scrolling
xinput --set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1 # Enable trackpad tap-to-click
xrdb -load $HOME/.config/X11/Xresources & # Load .Xresources

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh # Required for gnome-keyring to work correctly

sleep 1 && # Give xrdb a moment to load .Xresources
exec i3 # Start i3
