Order = [ "Tasha", "Weather", "Date" ]

[Tasha]
Script = "printf \"I love Tasha!\""
Interval = -1
ForegroundColor = "#f771f7"
BackgroundColor = ""
BorderColor = ""
SeparatorAfter = true

[Weather]
Script = "curl --silent \"wttr.in?format=\"%l:+%C+%t\"\""
Interval = 300000
ForegroundColor = "#99cc99"
BackgroundColor = ""
BorderColor = ""
SeparatorAfter = true

[Date]
Script = "date +\"%l:%M:%S%p %Y-%m-%d\""
Interval = 1000
ForegroundColor = "#cc99cc"
BackgroundColor = ""
BorderColor = ""
SeparatorAfter = true
