[General]
RefreshTime = 1000

### SCHEMA ###
# [[StatusItems]]
# Script = ""
# Interval = 0
# ForegroundColor = ""
# BackgroundColor = ""
# BorderColor = ""
# BorderWidthTop = 0
# BorderWidthBottom = 0
# BorderWidthLeft = 0
# BorderWidthRight = 0
# MinimumWidth = 0
# Alignment = ""
# Name = ""
# Instance = ""
# Urgent = false
# SeperatorAfter = true
# SeparatorBlockWidth = 9

[[StatusItems]]
Script = "printf \"I love Tasha!\""
Interval = -1
ForegroundColor = "#f771f7"
BackgroundColor = ""
BorderColor = ""
BorderWidthTop = 0
BorderWidthBottom = 0
BorderWidthLeft = 0
BorderWidthRight = 0
MinimumWidth = 0
Alignment = ""
Name = ""
Instance = ""
Urgent = false
SeperatorAfter = true

[[StatusItems]]
Script = "curl --silent \"wttr.in?format=\"%l:+%C+%t\"\""
Interval = 300
ForegroundColor = "#99cc99"
BackgroundColor = ""
BorderColor = ""
BorderWidthTop = 0
BorderWidthBottom = 0
BorderWidthLeft = 0
BorderWidthRight = 0
MinimumWidth = 0
Alignment = ""
Name = ""
Instance = ""
Urgent = false
SeperatorAfter = true
SeparatorBlockWidth = 9

[[StatusItems]]
Script = "date +\"%l:%M:%S%p %Y-%m-%d\""
Interval = 1
ForegroundColor = "#cc99cc"
BackgroundColor = ""
BorderColor = ""
BorderWidthTop = 0
BorderWidthBottom = 0
BorderWidthLeft = 0
BorderWidthRight = 0
MinimumWidth = 0
Alignment = ""
Name = ""
Instance = ""
Urgent = false
SeperatorAfter = true
SeparatorBlockWidth = 9
