Order = [ "Tasha", "VPN", "Memory", "Date" ]

[Tasha]
Script = "printf \"I love Tasha!\""
Interval = -1
ForegroundColor = "#f771f7"
BackgroundColor = ""
BorderColor = ""
SeparatorAfter = true

[VPN]
Script = "printf \"IP Location: $(curl --silent https://am.i.mullvad.net/city), $(curl --silent https://am.i.mullvad.net/country)\""
Interval = 5000
ForegroundColor = "#99cc99"
BackgroundColor = ""
BorderColor = ""
SeparatorAfter = true

[Memory]
Script = "echo 'Available Memory:' $(free -h | awk -F' ' 'NR==2 {print $7}')"
Interval = 3000
ForegroundColor = "#6699cc"
BackgroundColor = ""
BorderColor = ""
SeparatorAfter = true

[Date]
Script = "date +\"%l:%M:%S%p %Y-%m-%d\""
Interval = 1000
ForegroundColor = "#cc99cc"
BackgroundColor = ""
BorderColor = ""
SeparatorAfter = true
