require('autocommands')
require('commands')
require('plugins')
require('options')
require('keys')
require('colors')
require('style')

require('plugin-conf.telescope')
require('plugin-conf.lspconfig')
require('plugin-conf.cmp')
require('plugin-conf.aerial')
