require('plugins')
require('options')
require('keys')
require('colors')
require('style')

require('plugin-conf.treesitter')
require('plugin-conf.telescope')
require('plugin-conf.lspconfig')
require('plugin-conf.cmp')
require('plugin-conf.lualine')
require('plugin-conf.navic')
require('plugin-conf.aerial')
