add_newline = false # Don't print a new line at the start of the prompt

# PWD settings
[directory]
style = "bold blue"
truncate_to_repo = false

[git_status]
ahead = "↑"
behind = "↓"
diverged = "↕"

[cmake]
disabled = true
