export HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=65536
SAVEHIST=65536

# Completion
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle :compinstall filename '/home/james/.zshrc'
autoload -Uz compinit
compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION

# Module to ctrl+w to last slash or last space
autoload -U select-word-style
select-word-style bash

# Defaults
export EDITOR=nvim
export TERMINAL=alacritty
export BROWSER=firefox

# Aliases
alias vim="nvim"
alias cat="bat --theme=base16 --paging=never"
alias ls="exa --color=auto"
alias l="exa -lah --color=auto"
alias gs="git status"
alias gd="git diff"
alias mv="mv -iv"
alias rm="rm -iv"
alias cp="cp -iv"
alias startx="startx "$XINITRC""
alias grep="rg"

# Use neovim as the man pager
export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Keybinds
bindkey "^[[1;5C" 	forward-word # Ctrl+Right
bindkey "^[[1;5D" 	backward-word # Ctrl+Left
bindkey "^[[H" 	    beginning-of-line # Home
bindkey "^[[F" 	    end-of-line # End
bindkey "^[[2~" 	overwrite-mode # Insert
bindkey "^[[3~" 	delete-char # Delete
bindkey "^[[5~" 	beginning-of-history #PageUp
bindkey "^[[6~" 	end-of-history #PageDown
bindkey "^[[Z"      reverse-menu-complete # Shift+Tab

# Starship prompt
eval "$(starship init zsh)"

# Base16-Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"
base16_eighties

# zsh-syntax-highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# fzf
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
export FZF_DEFAULT_OPTS="--color=16 --info=inline"
export FZF_PREVIEW_COMMAND="bat --style=numbers --theme=base16 --color=always \$FILE" # Sets the default preview options for fzf.vim
