HISTFILE=~/.zsh_hist
HISTSIZE=65536
SAVEHIST=65536

# Completion
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename '/home/james/.zshrc'
autoload -Uz compinit
compinit

# Module to ctrl+w to last slash or last space
autoload -U select-word-style
select-word-style bash

# Aliases
alias vim="nvim"
alias ls="ls --color=auto"
alias l="ls -la --color=auto"

# Keybinds
bindkey "^[[1;5C" 	forward-word # Ctrl+Right
bindkey "^[[1;5D" 	backward-word # Ctrl+Left
bindkey "^[[7~" 	beginning-of-line # Home
bindkey "^[[8~" 	end-of-line # End
bindkey "^[[2~" 	overwrite-mode # Insert
bindkey "^[[3~" 	delete-char # Delete
bindkey "^[[5~" 	beginning-of-history #PageUp
bindkey "^[[6~" 	end-of-history #PageDown

# Starship prompt
eval "$(starship init zsh)"

# Base16-Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"
base16_eighties

# zsh-syntax-highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
