#!/bin/sh

xrdb -load "${XDG_CONFIG_HOME}/X11/Xresources" # Load Xresources

. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh # Required for gnome-keyring to work correctly

xrandr --fb 5460x2880 \
    --output DP-0 --pos 1620x360 --mode 3840x2160 --scale 1x1 --primary \
    --output HDMI-0 --pos 0x0 --mode 1920x1080 --scale 1.5x1.5 --rotate left # Setup displays

exec i3 # Start i3
